// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Course_Display.Data
{
    public partial class CoursedbContext : DbContext
    {
        public CoursedbContext()
        {
        }

        public CoursedbContext(DbContextOptions<CoursedbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Course> CISTList { get; set; }
        public virtual DbSet<ReqCourse> CoreCourses { get; set; }
        public virtual DbSet<ReqCourse> CoreExtension { get; set; }
        public virtual DbSet<Course> CSCIList { get; set; }
        public virtual DbSet<Course> CYBRList { get; set; }
        public virtual DbSet<Course> MATHList { get; set; }
        public virtual DbSet<ReqCourse> UpperDivision { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Course>(entity =>
            {
                entity.HasKey(e => e.CourseName)
                    .HasName("PK__CISTList__9526E276BFF2B672");

                entity.ToTable("CISTList");

                entity.Property(e => e.CourseName).HasMaxLength(50);

                entity.Property(e => e.Prereqs).HasMaxLength(75);
            });

            modelBuilder.Entity<ReqCourse>(entity =>
            {
                entity.HasKey(e => e.CourseName)
                    .HasName("PK__CoreCour__9526E27698664223");

                entity.Property(e => e.CourseName).HasMaxLength(50);
            });

            modelBuilder.Entity<ReqCourse>(entity =>
            {
                entity.HasKey(e => e.CourseName)
                    .HasName("PK__CoreExte__9526E276B5899F38");

                entity.Property(e => e.CourseName).HasMaxLength(50);
            });

            modelBuilder.Entity<Course>(entity =>
            {
                entity.HasKey(e => e.CourseName)
                    .HasName("PK__Table__9526E27677206980");

                entity.ToTable("CSCIList");

                entity.Property(e => e.CourseName).HasMaxLength(50);

                entity.Property(e => e.Prereqs).HasMaxLength(75);
            });

            modelBuilder.Entity<Course>(entity =>
            {
                entity.HasKey(e => e.CourseName)
                    .HasName("PK__CYBRList__9526E2761FD29BBC");

                entity.ToTable("CYBRList");

                entity.Property(e => e.CourseName).HasMaxLength(50);

                entity.Property(e => e.Prereqs).HasMaxLength(75);
            });

            modelBuilder.Entity<Course>(entity =>
            {
                entity.HasKey(e => e.CourseName)
                    .HasName("PK__MATHList__9526E27627CFB7BB");

                entity.ToTable("MATHList");

                entity.Property(e => e.CourseName).HasMaxLength(50);

                entity.Property(e => e.Prereqs).HasMaxLength(75);
            });

            modelBuilder.Entity<ReqCourse>(entity =>
            {
                entity.HasKey(e => e.CourseName)
                    .HasName("PK__UpperDiv__9526E2769C815BF0");

                entity.Property(e => e.CourseName).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}