name: Course_Display
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build site
      run: npm run build
    - name: Publish Blazor webassembly using dotnet
      run: dotnet publish -c Release --no-build -o ./../CourseDisplay/
    - name: Publish generated Blazor webassembly to Netlify

      env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run:  npx netlify-cli deploy --dir=Course_Display/ --prod
